### ISSUE TITLE
More information required

### ISSUE THREAD

**Issue by DreamWaterFound** [Factor-Robotics/Roller-Coaster-SLAM-Dataset#1]
Hello,

I've been diving into your Roller Coaster SLAM Dataset repo (super cool, btw!) and noticed a few things that might need your attention:

1. The Readme's got a couple of links that seem to be taking me on a wild YouTube ride to some unrelated videos. Might we need to tweak those?
![Screenshot from 2024-01-02 15-51-20](https://github.com/Factor-Robotics/Roller-Coaster-SLAM-Dataset/assets/33981288/f2cab812-7574-408f-a5db-73f75c079575)

2. Noticed in the darker environments, the stereo images are like a starry night - full of noise. What's up with that?

![Peek 2024-01-02 15-53](https://github.com/Factor-Robotics/Roller-Coaster-SLAM-Dataset/assets/33981288/647134c4-c98b-4c7b-94eb-6b72b8fd5107)

3. About the sensor placement - any chance we could get more deets on why they're angled the way they are? And maybe where exactly they're chilling on the coaster? Could you provide a diagram similar to the one below, showing the sensor installation positions?

![Screenshot from 2024-01-02 15-55-47](https://github.com/Factor-Robotics/Roller-Coaster-SLAM-Dataset/assets/33981288/cdb14910-e4a8-4db1-a3f0-56dc2dc137c2)

4. Lastly, for us algorithm geeks, how can we get our hands on the reference trajectory for this wild ride?

Thanks a bunch for your work, and looking forward to making this dataset even more awesome!

Cheers!

**Comment by borongyuan** [comment]
> 2\. Noticed in the darker environments, the stereo images are like a starry night - full of noise. What's up with that?

A large amount of noise is expected in dark light environments, which is also one of the challenges of this sequence.

> 3\. About the sensor placement - any chance we could get more deets on why they're angled the way they are? And maybe where exactly they're chilling on the coaster? Could you provide a diagram similar to the one below, showing the sensor installation positions?

The OAK camera attaches to my hand via an action camera wristband. Since this roller coaster vehicle is in the shape of a motorcycle, my hand is tilted when I grab the handle.

> 4\. Lastly, for us algorithm geeks, how can we get our hands on the reference trajectory for this wild ride?

There is no reference or ground truth. Therefore other performance evaluation criteria need to be considered.

**Comment by DreamWaterFound** [comment]
Thanks for the clarifications!
